spec_version: v1
style: planner
structured_output: {type: "object", additionalProperties: false, properties: {data: {type: "array", items: {type: "object", additionalProperties: false, properties: {supplier_name: {type: "string"}, country: {type: "string"}, delivery_days: {type: "number"}}}}}}
name: Product_Supplier_Info_Agent_planner
llm: watsonx/meta-llama/llama-3-2-90b-vision-instruct
description: |
  Planner agent that returns supplier directory details as a flat JSON array.

instructions: |
  - Call get_supplier_countries and get_supplier_delivery_days (and get_supplier_names if needed for the union).
  - Merge by supplier_name and return {"data": [{supplier_name, country, delivery_days}]} as JSON.

tools:
  - get_supplier_names
  - get_supplier_countries
  - get_supplier_delivery_days
