---
# Create Vault user and group

- name: Create Vault group
  group:
    name: "{{ vault_group }}"
    state: present
    system: yes

- name: Create Vault user
  user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    system: yes
    shell: /bin/false
    home: "{{ vault_data_dir }}"
    createhome: no
    comment: "Vault service user"

# Made with Bob
