from __future__ import annotations

import hashlib
import logging
import queue
import threading
import time
from datetime import datetime, timezone
from typing import Any
from uuid import uuid4

from app.config import Settings
from app.models import KnowledgeChunk, KnowledgeDocument, RagAnswer, RagQuestion
from app.services.chunking import chunk_text
from app.services.embedding import HashEmbeddingModel
from app.services.kafka import KafkaGateway
from app.services.llm import GroundedGenerator
from app.services.vector_index import VectorIndex

LOGGER = logging.getLogger(__name__)


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


class LocalContinuousRagIndexer:
    """Continuously turns raw knowledge events into chunk embeddings on Kafka."""

    def __init__(self, settings: Settings, kafka: KafkaGateway, embedder: HashEmbeddingModel):
        self.settings = settings
        self.kafka = kafka
        self.embedder = embedder

    def start(self) -> None:
        self.kafka.start_consumer(
            self.settings.topic_knowledge_raw,
            "factorypulse-local-rag-indexer-v1",
            self._on_document,
            auto_offset_reset="earliest",
        )

    def _on_document(self, payload: dict[str, Any]) -> None:
        document = KnowledgeDocument.model_validate(payload)
        chunks = chunk_text(
            document.text,
            chunk_size=self.settings.rag_chunk_size,
            overlap=self.settings.rag_chunk_overlap,
        )
        LOGGER.info("Indexing document=%s chunks=%s", document.document_id, len(chunks))
        for ordinal, text in enumerate(chunks):
            chunk_key = f"{document.document_id}:{ordinal}:{text}"
            chunk_id = hashlib.sha256(chunk_key.encode("utf-8")).hexdigest()[:32]
            chunk = KnowledgeChunk(
                chunk_id=chunk_id,
                document_id=document.document_id,
                title=document.title,
                text=text,
                source=document.source,
                asset_id=document.asset_id,
                updated_at=document.updated_at,
                metadata={**document.metadata, "chunk_ordinal": ordinal},
                embedding=self.embedder.embed(text),
                embedding_model=self.embedder.name,
            )
            self.kafka.produce(
                self.settings.topic_knowledge_embeddings,
                chunk.model_dump(),
                key=chunk.chunk_id,
            )
        self.kafka.flush(5)


class QueryEmbeddingBroker:
    """Correlates web requests with query embeddings generated by Confluent Flink."""

    def __init__(self, settings: Settings, kafka: KafkaGateway):
        self.settings = settings
        self.kafka = kafka
        self._waiters: dict[str, queue.Queue[list[float]]] = {}
        self._lock = threading.RLock()

    def start(self) -> None:
        self.kafka.start_consumer(
            self.settings.topic_query_embeddings,
            f"factorypulse-query-embeddings-{self.settings.instance_id}",
            self._on_embedding,
            auto_offset_reset="latest",
        )

    def _on_embedding(self, payload: dict[str, Any]) -> None:
        request_id = payload.get("request_id")
        if not request_id:
            return
        with self._lock:
            waiter = self._waiters.get(request_id)
        if waiter:
            waiter.put([float(value) for value in payload.get("embedding", [])])

    def embed(self, question: str, timeout: float = 25.0) -> list[float]:
        request_id = str(uuid4())
        waiter: queue.Queue[list[float]] = queue.Queue(maxsize=1)
        with self._lock:
            self._waiters[request_id] = waiter
        try:
            self.kafka.produce(
                self.settings.topic_query_requests,
                {
                    "request_id": request_id,
                    "instance_id": self.settings.instance_id,
                    "question": question,
                    "ts": utc_now_iso(),
                },
                key=request_id,
            )
            self.kafka.flush(5)
            return waiter.get(timeout=timeout)
        except queue.Empty as exc:
            raise TimeoutError(
                "Timed out waiting for Confluent Flink query embedding. "
                "Check infra/flink/continuous_rag.sql and the running statement."
            ) from exc
        finally:
            with self._lock:
                self._waiters.pop(request_id, None)


class RagService:
    def __init__(
        self,
        settings: Settings,
        kafka: KafkaGateway,
        index: VectorIndex,
        generator: GroundedGenerator,
    ) -> None:
        self.settings = settings
        self.kafka = kafka
        self.index = index
        self.embedder = HashEmbeddingModel(settings.rag_embedding_dim)
        self.generator = generator
        self.query_broker = QueryEmbeddingBroker(settings, kafka)
        self.indexer = LocalContinuousRagIndexer(settings, kafka, self.embedder)

    def start(self) -> None:
        self.kafka.start_consumer(
            self.settings.topic_knowledge_embeddings,
            f"factorypulse-index-view-{self.settings.instance_id}",
            self._on_chunk,
            auto_offset_reset="earliest",
        )

        if self.settings.rag_pipeline_mode.lower() == "local":
            self.indexer.start()
        elif self.settings.rag_pipeline_mode.lower() == "flink":
            self.query_broker.start()
        else:
            raise ValueError("RAG_PIPELINE_MODE must be either 'local' or 'flink'.")

    def _on_chunk(self, payload: dict[str, Any]) -> None:
        try:
            chunk = KnowledgeChunk.model_validate(payload)
            self.index.upsert(chunk)
        except Exception:
            LOGGER.exception("Invalid knowledge embedding record")

    def ask(self, question: RagQuestion) -> RagAnswer:
        started = time.perf_counter()
        if self.settings.rag_pipeline_mode.lower() == "flink":
            query_embedding = self.query_broker.embed(question.question)
            retrieval_mode = "confluent-flink-ai-embedding + kafka-backed-index"
        else:
            query_embedding = self.embedder.embed(question.question)
            retrieval_mode = "continuous-kafka-index + demo-hash-embedding"

        evidence = self.index.search(query_embedding, top_k=question.top_k, query_text=question.question)
        answer, generation_mode = self.generator.generate(question.question, evidence)
        latency_ms = int((time.perf_counter() - started) * 1000)
        return RagAnswer(
            answer=answer,
            evidence=evidence,
            retrieval_mode=retrieval_mode,
            generation_mode=generation_mode,
            latency_ms=latency_ms,
        )
