apiVersion: v1
kind: Secret
metadata:
  name: <name_of_secret>
  namespace: <openshift-project>
type: Opaque
stringData:
  APP_API_KEY: 
  IBM_CLOUD_API_KEY: 
  TEXT_TO_SQL_ENDPOINT: https://api.ca-tor.dai.cloud.ibm.com/semantic_automation/v1/text_to_sql
  WXD_PROJECT_ID: 
  PRESTO_HOSTNAME: 
  PRESTO_PORT: 
  PRESTO_USERNAME:
  PRESTO_PASSWORD:
  PRESTO_CATALOG:
  PRESTO_SCHEMA:
  PRESTO_TLS_LOCATION:
