name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write   # Allow pushing to gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Optional - if you’re using a build tool like gitlanding or React
      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Build Site
        run: |
          mkdir -p build
          echo "<h1>IBM Building Blocks</h1><p>Welcome to the AI & Automation Framework</p>" > build/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

