name: Deploy Building Blocks Landing Page

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build static site
        run: |
          mkdir -p bin
          cp -r build/index.html  bin
          cp -r build/css bin
          cp -r build/js bin
          cp -r build/images bin
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./bin

